# Markdown lint ruleset for consistent, “perfect” Markdown across the repo.
# Compatible with markdownlint/markdownlint-cli and markdownlint-cli2.

# Start from defaults and tune selectively.
default: true

# Line length: keep prose readable but don’t flag code blocks or tables.
MD013:
  line_length: 120
  heading_line_length: 120
  code_blocks: false
  tables: false

# Headings and structure.
MD001: true
MD003:
  style: atx
MD022: true
MD025: true
MD026:
  punctuation: ".,;:!。，；：！"
MD024:
  siblings_only: true

# Lists and spacing.
MD004:
  style: dash
MD007:
  indent: 2
MD029:
  style: one

# Code blocks and HTML.
MD031: true
MD046:
  style: fenced
MD048:
  style: backtick
MD033: false

# Links and URLs.
MD034: true

# First line must be a top-level heading.
MD041: true
